### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by dmiret** [dmiret/Zork-Project#14]

**Comment by caitlynmei** [comment]
I made the ignoreWords set

**Comment by caitlynmei** [comment]
Research about how everything in Parser file links together @dmiret

**Comment by caitlynmei** [comment]
I researched about sentence trees!! I know how to read them!

**Comment by wesley-a-leung** [comment]
2 questions:
1. What are sentence trees?
2. What is the purpose of them?

**Comment by dmiret** [comment]
Would you like to write the code for it?

**Comment by caitlynmei** [comment]
@wesley-a-leung Ha! I knew something Wesley didn't.

**Comment by ggerges** [comment]
Yay! I'm just watching !

**Comment by caitlynmei** [comment]
@dmiret Like you know what sentence tree is

**Comment by wesley-a-leung** [comment]
Well this can't be good
