### ISSUE TITLE
Draw a map of the area 

### ISSUE THREAD

**Issue by caitlynmei** [dmiret/Zork-Project#3]
After our storyline is finished I'm going to draw everything (birds eye view) and actual rooms with furniture and stuff. I'll post it on Github later. @ggerges @dmiret @jennifertran105

**Comment by ggerges** [comment]
sounds good

**Comment by ggerges** [comment]
![20170424_144820](https://cloud.githubusercontent.com/assets/22034690/25353612/e37b0532-28fd-11e7-808e-b64f8cf5021f.jpg)
