### ISSUE TITLE
Items we are going to have in the game 

### ISSUE THREAD

**Issue by ggerges** [dmiret/Zork-Project#33]
Can someone make a list of the items we are going to use in the game? I can make the classes for all of them. 

Just did. It's called itemList.dat - CM

**Comment by caitlynmei** [comment]
@ggerges Wow, assign everyone but yourself

**Comment by ggerges** [comment]
@caitlynmei cause im gonna do the classes for them I don't wanna think of them ;)

**Comment by caitlynmei** [comment]
@ggerges Sure sure. Do the easy robotic part. 😒

**Comment by caitlynmei** [comment]
I just finished the list of items needed in level 2

**Comment by ggerges** [comment]
@caitlynmei you're my favourite
